Added Project Files
Divyan-H/auroville-vision-page-clone pull request #1
Opened 2023-07-11 08:42 UTC by Divyan-H

Team, kindly review my code and provide necessary feedback for improvements. Your suggestions are valuable in enhancing its quality. Thank you for your assistance in making it even better.

file:///home/divyan/Pictures/Screenshots/Screenshot%20from%202023-07-11%2014-07-58.png

2023-07-19 11:13 UTC, sangeethailango requested changes

2023-07-19 11:13 UTC, sangeethailango commented on index.html
> +        <div id="the-mother">The Mother</div>
Indent the whole code properly.

2023-07-19 11:13 UTC, sangeethailango commented on index.html
> +        </div>
Good indentation.

2023-07-19 11:13 UTC, sangeethailango commented on index.html
> +                <img src="https://files.auroville.org/auroville-org/a21d0974-55b2-4ab3-ab62-ced4db9c90be.jpg"
Use relative file paths for all of the images which is in this page. Read the below documentation on file paths.
https://www.w3schools.com/html/html_filepaths.asp

2023-07-20 10:52 UTC, sakthibalan15 approved these changes

2023-07-21 08:45 UTC, nittin-shankar approved these changes
If you do all the changes that @sangeethailango has given, you're good to merge it.

2023-07-25 10:14 UTC, merged